---
title: "linear_models"
author: "Pei Yang Hsieh"
date: 2018-11-8
output: html_document
---

```{r}
library(tidyverse)
library(p8105.datasets)
```


## Example 1

```{r}
set.seed(1)

data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(boro = neighbourhood_group,
         neighborhood = neighbourhood) %>% 
  filter(boro != "Staten Island") %>% 
  select(price, stars, boro, neighborhood, room_type)

fit = lm(price ~ stars + boro, data = nyc_airbnb)
```


```{r}
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(boro = fct_infreq(boro),
         room_type = fct_infreq(room_type))

fit = lm(price ~ stars + boro, data = nyc_airbnb)
```



```{r}
summary(fit)
summary(fit)$coef
coef(fit)
#fitted.values(fit)
```


```{r}
#glance extracts quick summaries related to model fit
fit %>% 
  broom::glance()

fit %>% 
  broom::tidy()
```


better summary


```{r}
#Manhattan is your reference point. all the others are cheaper (negative estimates) than Manhattan
fit %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  mutate(term = str_replace(term, "^boro", "Boro: ")) %>% 
  knitr::kable(digits = 3)
```



## Diagnostics

```{r}
#adds a residuals column
modelr::add_residuals(nyc_airbnb, fit)

modelr::add_predictions(nyc_airbnb, fit)

nyc_airbnb %>% 
  modelr::add_residuals(fit) %>% 
  ggplot(aes(x = boro, y = resid)) + geom_violin()
```

```{r}
nyc_airbnb %>% 
  modelr::add_residuals(fit) %>% 
  ggplot(aes(x = stars, y = resid)) + geom_point()
```


## Hypothesis Testing

```{r}
fit_null = lm(price ~ stars + boro, data = nyc_airbnb)
fit_alt = lm(price ~ stars + boro + room_type, data = nyc_airbnb)

anova(fit_null, fit_alt) %>% 
  broom::tidy()
```



## Nesting Data

```{r}
#testing boro might affect stars and boro might affect room type in different ways
nyc_airbnb %>% 
  lm(price ~ stars * boro + room_type * boro, data = .) %>% 
  broom::tidy() %>% 
  knitr::kable(digits = 3)
```

